### PR TITLE
cmake: FindPKCS11: only set if PKCS11_MODULE isn't set already

### PR DESCRIPTION
**Pull request by flokli**
Alternative to https://github.com/open-eid/cmake/pull/34.

This allows manually configuring a path, by invoking cmake with
`-DPKCS11_MODULE=/path/to/module` parameters.

### CODE REVIEW

**Comment by flokli** [comment]
@metsma what's the state of this?

**Comment by klemensn** [comment]
FWIW, I'm with this PR instead of #34.

**Comment by metsma** [comment]
@klemensn can you close then the other PR
@flokli can you fix the whitespace chars

**Comment by klemensn** [comment]
> @klemensn can you close then the other PR

Done.

> @flokli can you fix the whitespace chars

I don't see anything to fix.

**Comment by flokli** [comment]
> I don't see anything to fix.

This was referring to the mixed tabs and spaces in front of the `set(PKCS11_MODULE opensc-pkcs11…` lines.

I made it all tabs, to be consistent with the rest of that file.

**Review by metsma — APPROVED** [review]

**Comment by klemensn** [comment]
On OpenBSD I'm now linking with OpenSC's directory added to the runtime path
instead of this patch and a compile-time option to specify the module.

The proposed option assumes that one module is enough and exists, but it
might be preferrable to have a list of modules (in order of preference) and
use the first one that is found at runtime.

I still don't quite understand why**, but there is more code to load modules
at runtime which does not seem effected by this CMake code
(see https://github.com/open-eid/DigiDoc4-Client/pull/1078).

**I had assumed that libdigidocpp would be the only piece of code that loads
PKCS#11 modules, such that all cients (digidoc-tool(1), qdigidoc4(1), etc.)
share it and don't have to reimplement parts of it.

**Comment by klemensn** [comment]
Once fixes like https://github.com/open-eid/DigiDoc4-Client/pull/1078 make it into the tree, there should be nothing for distribution packageers to patch or fix after building open-eid's stack -- given they linked with the right runtime paths, of course.

**Pull request merged**
